on:
  push:
    branches:
      - main
  pull_request:

name: Pysa

jobs:
  pysa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Pysa Action
        uses: facebook/pysa-action@main
        with:
          repo-directory: './'
          requirements-path: 'requirements.txt'
